// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.cs.CommonUtil {
    public class VersionInfo {
        public static string appVersion = "2.0.1";
        public static string longVersion = "2.0.1-20220503-b5d8f82a";
        public static string buildDate = "20220503";
    }
}
